export const PAINTINGS = [
    {
      title: 'Hallway',
      artist: 'Efe Kurnaz',
      src: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Volutpat sed cras ornare arcu dui. Ac feugiat sed lectus vestibulum.',
      price: '$899.99',
      avgRating: 4.8,
      reviews: 445,
      inStock: true,
      readyForPickup: true,
      bestSeller: true,
      isNew: false,
      limitedSupply: false,
    },
    {
      title: 'Fire and Ice',
      artist: 'Pawel Czerwinski',
      src: 'https://images.unsplash.com/photo-1604871000636-074fa5117945?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987',
      description:
        'Lorem ipsum dolor sit amet, ubique patrioque at qui, modo hinc ne duo, ad consul animal volumus est. Ea quo etiam deleniti, amet singulis in sed. Omnesque lobortis vis ex. Wisi latine splendide vis ei, libris commodo no has.',
      price: '$699.99',
      avgRating: 4.1,
      reviews: 222,
      inStock: true,
      readyForPickup: true,
      bestSeller: false,
      isNew: false,
      limitedSupply: false,
    },
    {
      title: 'Orange, pink, yellow',
      artist: 'Kseniya Lapteva',
      src: 'https://images.unsplash.com/photo-1629196914375-f7e48f477b6d?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1306',
      description:
        'Lorem ipsum dolor sit amet, cu porro vivendum ius. Ad mei sint homero, cum an soluta epicurei. At pri minimum corrumpit. Minim percipitur eu mei, erant habemus deserunt qui et.',
      price: '$139.99',
      avgRating: 3.5,
      reviews: 142,
      inStock: true,
      readyForPickup: false,
      bestSeller: false,
      isNew: true,
      limitedSupply: false,
    },
    {
      title: 'Melted Purple',
      artist: 'Maria Orlova',
      src: 'https://images.unsplash.com/photo-1549490349-8643362247b5?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987',
      description:
        'Lorem ipsum dolor sit amet, facer nemore ei sea, mea facilis eloquentiam at. Et modus pertinax tincidunt est. Propriae argumentum necessitatibus eos ad.',
      price: '$499.99',
      avgRating: 4.5,
      reviews: 301,
      inStock: true,
      readyForPickup: true,
      bestSeller: true,
      isNew: false,
      limitedSupply: false,
    },
    {
      title: 'Experimental',
      artist: 'Bruno Thethe',
      src: 'https://images.unsplash.com/photo-1550275994-cdc89cd1948f?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987',
      description:
        'Lorem ipsum dolor sit amet, ea probo choro tollit pri, ad pro justo intellegam repudiandae, labores civibus eu quo. Cum latine instructior at, est no odio tibique epicuri.',
      price: '$159.99',
      avgRating: 3.1,
      reviews: 56,
      inStock: true,
      readyForPickup: true,
      bestSeller: false,
      isNew: true,
      limitedSupply: false,
    },
    {
      title: 'Rainbow',
      artist: 'Felix Spiske',
      src: 'https://images.unsplash.com/photo-1543857778-c4a1a3e0b2eb?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1310',
      description:
        'Lorem ipsum dolor sit amet, sea tritani indoctum cu, facilis praesent at qui. Cu cetero veritus vel, et prima erant perfecto vix. Tollit delectus scaevola duo et, inermis sensibus voluptatum cu ius.',
      price: '$799.99',
      avgRating: 4.9,
      reviews: 550,
      inStock: true,
      readyForPickup: false,
      bestSeller: true,
      isNew: false,
      limitedSupply: true,
    },
    {
      title: 'Fearless Hue',
      artist: 'Radienta',
      src: 'https://images.unsplash.com/photo-1579547621113-e4bb2a19bdd6?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=939',
      description:
        'Lorem ipsum dolor sit amet, te labore lucilius pro, te his consul singulis, cu vel unum impedit complectitur. In usu erat dicta doctus, purto aeterno vis te. Facete deterruisset nec id. At omittam antiopam pri.',
      price: '$249.99',
      avgRating: 3.3,
      reviews: 294,
      inStock: true,
      readyForPickup: true,
      bestSeller: false,
      isNew: false,
      limitedSupply: false,
    },
    {
      title: 'Liquid',
      artist: 'Joel Filipe',
      src: 'https://images.unsplash.com/photo-1485163819542-13adeb5e0068?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987',
      description:
        'Lorem ipsum dolor sit amet, cum cu meliore tacimates, vel no sale maiorum. His cu autem placerat. Homero urbanitas vituperata ad sit, ex mel convenire elaboraret.',
      price: '$549.99',
      avgRating: 4.5,
      reviews: 440,
      inStock: false,
      readyForPickup: false,
      bestSeller: false,
      isNew: false,
      limitedSupply: true,
    },
  ];

export const POTTERY = [
    {
      title: 'Ceramic Vase',
      artist: 'Anna Smith',
      src: 'https://i.pinimg.com/736x/31/31/45/313145ba3aa3db9e889dd637b7e0b4b3.jpg',
      description:
        'A beautifully crafted ceramic vase, perfect for any home decor.',
      price: '$49.99',
      avgRating: 4.7,
      reviews: 120,
      inStock: true,
      readyForPickup: true,
      bestSeller: true,
      isNew: false,
      limitedSupply: false,
    },
    {
      title: 'Handmade Bowl',
      artist: 'John Doe',
      src: 'https://i.pinimg.com/736x/31/31/45/313145ba3aa3db9e889dd637b7e0b4b3.jpg',
      description:
        'A unique handmade bowl that adds a touch of elegance to your dining experience.',
      price: '$29.99',
      avgRating: 4.5,
      reviews: 85,
      inStock: true,
      readyForPickup: true,
      bestSeller: false,
      isNew: true,
      limitedSupply: false,
    },
    {
      title: 'Artistic Plate',
      artist: 'Emily Johnson',
      src: 'https://i.pinimg.com/736x/31/31/45/313145ba3aa3db9e889dd637b7e0b4b3.jpg',
      description:
        'An artistic plate that serves as a centerpiece for any table.',
      price: '$39.99',
      avgRating: 4.2,
      reviews: 60,
      inStock: true,
      readyForPickup: false,
      bestSeller: false,
      isNew: true,
      limitedSupply: true,
    },
    {
      title: 'Clay Mug',
      artist: 'Michael Brown',
      src: 'https://i.pinimg.com/736x/31/31/45/313145ba3aa3db9e889dd637b7e0b4b3.jpg',
      description:
        'A rustic clay mug, perfect for your morning coffee or tea.',
      price: '$19.99',
      avgRating: 4.8,
      reviews: 200,
      inStock: true,
      readyForPickup: true,
      bestSeller: true,
      isNew: false,
      limitedSupply: false,
    },
    {
      title: 'Decorative Jar',
      artist: 'Sophia Davis',
      src: 'https://i.pinimg.com/736x/31/31/45/313145ba3aa3db9e889dd637b7e0b4b3.jpg',
      description:
        'A decorative jar that can be used for storage or as a decorative piece.',
      price: '$34.99',
      avgRating: 4.3,
      reviews: 75,
      inStock: true,
      readyForPickup: true,
      bestSeller: false,
      isNew: true,
      limitedSupply: false,
    },
    {
      title: 'Flower Pot',
      artist: 'Liam Wilson',
      src: 'https://i.pinimg.com/736x/31/31/45/313145ba3aa3db9e889dd637b7e0b4b3.jpg',
      description:
        'A charming flower pot that enhances the beauty of your plants.',
      price: '$24.99',
      avgRating: 4.6,
      reviews: 150,
      inStock: true,
      readyForPickup: false,
      bestSeller: false,
      isNew: true,
      limitedSupply: true,
    },
    {
      title: 'Sculptural Piece',
      artist: 'Olivia Martinez',
      src: 'https://i.pinimg.com/736x/31/31/45/313145ba3aa3db9e889dd637b7e0b4b3.jpg',
      description:
        'A unique sculptural piece that serves as a conversation starter.',
      price: '$89.99',
      avgRating: 4.9,
      reviews: 90,
      inStock: true,
      readyForPickup: true,
      bestSeller: true,
      isNew: false,
      limitedSupply: false,
    },
    {
      title: 'Traditional Teapot',
      artist: 'James Garcia',
      src: 'https://i.pinimg.com/736x/31/31/45/313145ba3aa3db9e889dd637b7e0b4b3.jpg',
      description:
        'A traditional teapot that brings a touch of culture to your tea time.',
      price: '$59.99',
      avgRating: 4.4,
      reviews: 110,
      inStock: true,
      readyForPickup: true,
      bestSeller: false,
      isNew: false,
      limitedSupply: false,
    },
    {
      title: 'Miniature Figurine',
      artist: 'Isabella Rodriguez',
      src: 'https://i.pinimg.com/736x/31/31/45/313145ba3aa3db9e889dd637b7e0b4b3.jpg',
      description:
        'A delicate miniature figurine that adds charm to any collection.',
      price: '$14.99',
      avgRating: 4.1,
      reviews: 45,
      inStock: true,
      readyForPickup: false,
      bestSeller: false,
      isNew: true,
      limitedSupply: true,
    },
    {
      title: 'Pottery Set',
      artist: 'Ethan Lee',
      src: 'https://i.pinimg.com/736x/31/31/45/313145ba3aa3db9e889dd637b7e0b4b3.jpg',
      description:
        'A complete pottery set that includes various essential items.',
      price: '$199.99',
      avgRating: 4.8,
      reviews: 30,
      inStock: true,
      readyForPickup: true,
      bestSeller: true,
      isNew: false,
      limitedSupply: false,
    },
];

